name: DiT
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 2.5.1
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - timm
    - diffusers
    - accelerate
    - transformers
    - qwen-vl-utils
    - requests
    - matplotlib
    - tqdm
    - hydra-core
