_target_: datasets.build_clevr_dataset
datasets:
  - name: base
    path: /gscratch/scrubbed/sriyash/clevr_dit_dataset/data.zarr
    sampling_ratio: 0.75
    max_dataset_size: null
  - name: feedback
    path: /gscratch/scrubbed/sriyash/vlm_feedback_dataset/data.zarr
    sampling_ratio: 0.25
    max_dataset_size: null
split: train
image_size: ${model.image_size}
use_disk: true
load_meta: true
load_images: false
load_context: false
