hydra:
  job:
    chdir: false

data:
  split: train
  use_disk: true
  load_meta: true
  load_images: false
  load_context: false
  dataset_config:
    - name: base
      dataset_path: /gpfs/scrubbed/sriyash/clevr_dit_dataset/data.zarr
      sampling_ratio: 0.25
    - name: feedback
      dataset_path: /gpfs/scrubbed/sriyash/vlm_feedback_dataset_qwen/data.zarr
      sampling_ratio: 0.75

model:
  name: DiT-S/4
  image_size: 256
  num_classes: 1000
  vae: stabilityai/sdxl-vae
  context_dropout_prob: 0.1

train:
  results_dir: /gpfs/scrubbed/sriyash/DiT-qwen-clevr-feedback
  experiment_name: feedback_s4
  ckpt: /gpfs/scrubbed/sriyash/DiT-qwen-clevr-base/base_s4/checkpoints/0100000.pt
  epochs: 1000
  global_batch_size: 128
  global_seed: 0
  lr: 1e-5
  lr_schedule: cosine
  lr_warmup_steps: 2000
  min_lr: 1e-6
  min_lr_ratio: 0.1
  grad_clip: 1.0
  ema_decay: 0.999
  log_every: 100
  ckpt_every: 5000
  max_train_steps: 100000

dataloader:
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  drop_last: true

eval:
  split: val
  batch_size: 128
  max_batches_per_dataset: 64
  dataloader:
    num_workers: 2
    pin_memory: true
    persistent_workers: false
    prefetch_factor: 2

wandb:
  project: DiT-qwen-clevr
